dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install .
script: pytest
after_success:
  - pip install pytest-cov codecov
  - coverage run ./setup.py test > /dev/null
  - codecov --token=$CODECOV_TOKEN
